name: hello-world
on: [push]
jobs:
  Check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node_version: lts/*
      - name: Get Node.js versionS
        run: node -v
      - name: run hello-world.js
        run: node hello-world.js
