name: hello-world
on: [push]
jobs:
  Check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: check repo
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node_version: lts/*
      - run: node -v
      - run: node hello-world.js 
